<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="6" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="WebServiceTestSuite" duration-ms="28484" started-at="2019-08-14T10:18:43Z" finished-at="2019-08-14T10:19:12Z">
    <groups>
    </groups>
    <test name="RESTAPITest" duration-ms="28484" started-at="2019-08-14T10:18:43Z" finished-at="2019-08-14T10:19:12Z">
      <class name="tests.TestPUTRequest">
        <test-method status="PASS" signature="testPUTRequestDetails()[pri:0, instance:tests.TestPUTRequest@5827af16]" name="testPUTRequestDetails" duration-ms="6701" started-at="2019-08-14T10:19:01Z" finished-at="2019-08-14T10:19:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPUTRequestDetails -->
      </class> <!-- tests.TestPUTRequest -->
      <class name="tests.TestPOSTRequest">
        <test-method status="PASS" signature="testPOSTRequestDetails()[pri:0, instance:tests.TestPOSTRequest@62dae540]" name="testPOSTRequestDetails" duration-ms="5683" started-at="2019-08-14T10:18:55Z" finished-at="2019-08-14T10:19:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPOSTRequestDetails -->
      </class> <!-- tests.TestPOSTRequest -->
      <class name="tests.TestGETRequest">
        <test-method status="PASS" signature="setup()[pri:0, instance:tests.TestGETRequest@4bff1903]" name="setup" is-config="true" duration-ms="47" started-at="2019-08-14T10:18:43Z" finished-at="2019-08-14T10:18:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testGETUserDetails()[pri:0, instance:tests.TestGETRequest@4bff1903]" name="testGETUserDetails" duration-ms="11506" started-at="2019-08-14T10:18:43Z" finished-at="2019-08-14T10:18:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Name does not match expected [Eve2] but found [Eve]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Name does not match expected [Eve2] but found [Eve]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at tests.TestGETRequest.testGETUserDetails(TestGETRequest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGETUserDetails -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.TestGETRequest@4bff1903]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-08-14T10:19:12Z" finished-at="2019-08-14T10:19:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.TestGETRequest -->
      <class name="tests.TestDELETERequest">
        <test-method status="PASS" signature="testDELETERequestDetails()[pri:0, instance:tests.TestDELETERequest@654d8173]" name="testDELETERequestDetails" duration-ms="4312" started-at="2019-08-14T10:19:07Z" finished-at="2019-08-14T10:19:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDELETERequestDetails -->
      </class> <!-- tests.TestDELETERequest -->
    </test> <!-- RESTAPITest -->
  </suite> <!-- WebServiceTestSuite -->
</testng-results>
